name = "e7-edgesub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "EdgeSubDB"
id = "f977f2665ff6402e847cadea218e0883"
